// React/src/App.js
import React, { useState } from 'react';

import 'devextreme/dist/css/dx.light.css';

import { PieChart, Series, Label, Connector, Tooltip } from 'devextreme-react/pie-chart';
import { billionaires } from './data.js';

const customizeText = (pointInfo) => {
  return pointInfo.value + " billionaires";
}

const contentTemplate = (data) => {
  return data.argumentText;
}

const onPointClick = (e) => {
  const point = e.target;
  if (point.isSelected()) {
    point.clearSelection();
  } else {
    point.select();
  }
}

function App() {
  return (
    <div id="container">
      <PieChart
        dataSource={billionaires}
        type="doughnut"
        title="Top-5 Countries by Number of Billionaires"
        onPointClick={onPointClick}
      >
        <Series 
          argumentField="country" 
          valueField="amount"
        >
          <Label 
            visible={true}
            position="columns"
            customizeText={customizeText}
          >
            <Connector visible={true}></Connector>
          </Label>
        </Series>
        <Tooltip
          enabled={true}
          contentTemplate={contentTemplate}
        >
        </Tooltip>
      </PieChart>
    </div>
  );
}

export default App;

// Vue/src/App.vue
<template>
    <div id="container">
        <DxPieChart
            :data-source="billionaires"
            type="doughnut"
            title="Top-5 Countries by Number of Billionaires"
            @point-click="onPointClick"
        >
            <DxSeries
                argument-field="country"
                value-field="amount"
            >
                <DxLabel
                    :visible="true"
                    position="columns"
                    :customize-text="customizeText"
                >
                    <DxConnector :visible="true"></DxConnector>
                </DxLabel>
            </DxSeries>
            <DxTooltip
                :enabled="true"
                :content-template="contentTemplate"
            >
            </DxTooltip>
        </DxPieChart>
    </div>
</template>

<script>
    import { DxPieChart, DxSeries, DxLabel, DxConnector, DxTooltip } from 'devextreme-vue/pie-chart';
    import { billionaires } from './data.js';

    export default {
        components: {
            DxPieChart,
            DxSeries,
            DxLabel,
            DxConnector,
            DxTooltip
        },
        data() {
            return {
                billionaires
            };
        },
        methods: {    
            customizeText (pointInfo) {
                return pointInfo.value + " billionaires";
            },
            contentTemplate (data) {
                return data.argumentText;
            },
            onPointClick (e) {
                const point = e.target;
                if (point.isSelected()) {
                    point.clearSelection();
                } else {
                    point.select();
                }
            }
        }
    }
</script>

<style>
    #container {
        width: 600px;
    }
</style>
